FROM antoniopicone/flutter-web:0.4

# Added alias 'livecode' to execute web dev server
RUN echo 'alias livecode="flutter packages pub global run webdev serve --hostname 0.0.0.0 --auto restart"' >> ~/.bashrc